///*
// * This file was automatically generated by EvoSuite
// * Tue Jun 14 06:29:47 GMT 2022
// */
//
//package net.mooctest;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//import static org.evosuite.runtime.EvoAssertions.*;
//import java.io.FileNotFoundException;
//import java.io.IOException;
//import java.util.Set;
//import net.mooctest.Anagram;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.evosuite.runtime.testdata.EvoSuiteFile;
//import org.evosuite.runtime.testdata.FileSystemHandling;
//import org.junit.runner.RunWith;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
//public class Anagram_ESTest extends Anagram_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test0()  throws Throwable  {
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      byte[] byteArray0 = new byte[2];
//      byteArray0[0] = (byte) (-90);
//      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
//      Anagram anagram0 = new Anagram("IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      anagram0.findAllAnagrams("");
//      Set<Set<String>> set0 = anagram0.findAllAnagrams("?4~h");
//      assertEquals(0, set0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      Anagram anagram0 = new Anagram((-60), "IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      // Undeclared exception!
//      try { 
//        anagram0.findAllAnagrams((String) null);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("net.mooctest.Anagram", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test2()  throws Throwable  {
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(".\t");
//      FileSystemHandling.appendLineToFile(evoSuiteFile0, "s");
//      Anagram anagram0 = new Anagram(1743, ".\t");
//      FileSystemHandling.shouldAllThrowIOExceptions();
//      try { 
//        anagram0.findAllAnagrams("[Z");
//        fail("Expecting exception: IOException");
//      
//      } catch(IOException e) {
//         //
//         // Simulated IOException
//         //
//         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test3()  throws Throwable  {
//      Anagram anagram0 = new Anagram("Annotations are not supported.");
//      try { 
//        anagram0.findAllAnagrams("Annotations are not supported.");
//        fail("Expecting exception: FileNotFoundException");
//      
//      } catch(FileNotFoundException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test4()  throws Throwable  {
//      Anagram anagram0 = null;
//      try {
//        anagram0 = new Anagram((String) null);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test5()  throws Throwable  {
//      Anagram anagram0 = null;
//      try {
//        anagram0 = new Anagram(0, (String) null);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test6()  throws Throwable  {
//      Anagram anagram0 = null;
//      try {
//        anagram0 = new Anagram("");
//        fail("Expecting exception: AssertionError");
//      
//      } catch(AssertionError e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test7()  throws Throwable  {
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      byte[] byteArray0 = new byte[2];
//      byteArray0[1] = (byte) (-90);
//      FileSystemHandling.appendLineToFile(evoSuiteFile0, "i");
//      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
//      Anagram anagram0 = new Anagram((-27), "IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      Set<Set<String>> set0 = anagram0.findAllAnagrams("i");
//      assertFalse(set0.isEmpty());
//      
//      Set<Set<String>> set1 = anagram0.findAllAnagrams("L3?4~a~");
//      assertTrue(set1.isEmpty());
//  }
//
//  @Test(timeout = 4000)
//  public void test8()  throws Throwable  {
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      byte[] byteArray0 = new byte[8];
//      byteArray0[6] = (byte) (-74);
//      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
//      Anagram anagram0 = new Anagram("IGNORE_TYPE_VARIABLE_OR_WILDCARD");
//      anagram0.findAllAnagrams("");
//      Set<Set<String>> set0 = anagram0.findAllAnagrams("<k?");
//      assertEquals(0, set0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test9()  throws Throwable  {
//      Anagram anagram0 = null;
//      try {
//        anagram0 = new Anagram(0, "");
//        fail("Expecting exception: AssertionError");
//      
//      } catch(AssertionError e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//}
