# Generated by Django 4.0.4 on 2022-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
