# Generated by Django 4.0.4 on 2022-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
